dist: trusty
sudo: 'false'
language: node_js
node_js: node
cache: yarn
deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
  email:
    secure: vcDNJpkktJ2lB2KXeZz9Ym5xxJIm+ZiCrP2Ve6HXUb8ScQ7/pHbWVcdI4iiW+kT62MqHTISwyxSiRy1xzFUocA/Yie+0jgbWX1nCx6KjNWNk9TK9PKneys6/9mEmOUsK+iwMjRs0Tgj1D232kZEvrPOVEUao8/TIFXQ1usak79XnM+yZxDdquBTbeZjxxji9P0nnR0bmyj0M+h02xn2lf1vPOG8k5dpnuJ7jL5FfMG4dSObwpVO6EvOAguTbGFymfg0mG3oNpzmG6wurMivvzrHN/xuVSQw1rW0UPI1ucavgP0pueV0CXw8PdSLgZ80OU/5rmHwetxjCKdw/xQ5NuID3fF9p3vdXgxC5SfaVKmybvwwCJ0bW4p6qvPI516kDiTzg1u0/q3y7L2THA5TS7URYYHnRkL/Dco0AWwQzGlrZMyCE4waz84uPM5+5iK7xkN9VzemNhbDMRhCgIOuuLhF9DzkVg7rTHXu0eKpLuIyb7sVpN3Gaa9A/X9hxtaDWCd4ca1MYctU9Nrft3pTJ2AHfxgnX3cpQ1RK+rsCZ328XH3O7Dq7hWZjPEREUREhS/Q8cHEJW007S9U7UvY1exrp0BxUe9ZD5doXFzI4/Mdb5HbyCYWmvMqCjpdsnGtI2/Vrukupn8raY3pWzNCy6q4iKaJ7gSy8ritlqjqkH5Pc=
  api_key:
    secure: Vff2bV+3eeXSrJ3GWUDvTgX95sEhxCkl+ZkeSPFntrAjG+WntldYvEasOjJeelPXrH6ojZAeQy2XWhT5UDZ0pJpQYYR8bjd6YAukR6gfYp7dQRepwKs2ug/Nd5YPq1Nv3iYyD0yJ/Li8WVb7oLM5u+pWu7GWrCVTPxnnAXtDn5uaUOR5y9D3RTTdu81coRZKrF93mw+8LMJ2+Jvk7rCHGuPhYhYELEcmxNzH5AaVUE8Hl+avF0xL2+Q/apsB1Thgxm3kV1r18I+1BikXbEmK851I3vyyIJSRpyE4vlxWRpmqyvJFr9sYTKw6SDdLUhHhGmbuaX6N7SJ56POANkSswvmI+BUAX0KEKKq2xV9jJeYGn/QkM2nl5MRYuEqfITztHlzdtsSBzG6SUm0KDI/K3I9Zx1hIamf+IDR+mX5qBBFdhGe+0l6takap/kYZhiM5gTw7993vrbsSCHoRkLQ07avfuUwsyBQ/CrWs77LLHAQg5grfW8hMITms+uOGCIB1r9E5PoaH/i42AaHlX+Nr4iYb5UwlpXkUrR7wdbV6uxwxAoYBiCYjlj2cwuHnNGJjGox4ffgW3XnvmJmSQ0b0NGW9D5s/SzD5C8aF3ntAmkCCzLE3B48bftXwZcS6TnXRr0//5am9+NraXpm1xDgb9FP4M5x6EiQ9zRoysHazbQY=
